/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Tombola as PrismaTombola,
  Voucher as PrismaVoucher,
} from "@prisma/client";

export class TombolaServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.TombolaCountArgs, "select">): Promise<number> {
    return this.prisma.tombola.count(args);
  }

  async tombolas<T extends Prisma.TombolaFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TombolaFindManyArgs>
  ): Promise<PrismaTombola[]> {
    return this.prisma.tombola.findMany<Prisma.TombolaFindManyArgs>(args);
  }
  async tombola<T extends Prisma.TombolaFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TombolaFindUniqueArgs>
  ): Promise<PrismaTombola | null> {
    return this.prisma.tombola.findUnique(args);
  }
  async createTombola<T extends Prisma.TombolaCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TombolaCreateArgs>
  ): Promise<PrismaTombola> {
    return this.prisma.tombola.create<T>(args);
  }
  async updateTombola<T extends Prisma.TombolaUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TombolaUpdateArgs>
  ): Promise<PrismaTombola> {
    return this.prisma.tombola.update<T>(args);
  }
  async deleteTombola<T extends Prisma.TombolaDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.TombolaDeleteArgs>
  ): Promise<PrismaTombola> {
    return this.prisma.tombola.delete(args);
  }

  async findVouchers(
    parentId: string,
    args: Prisma.VoucherFindManyArgs
  ): Promise<PrismaVoucher[]> {
    return this.prisma.tombola
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .vouchers(args);
  }
}
