/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VoucherService } from "../voucher.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VoucherCreateInput } from "./VoucherCreateInput";
import { Voucher } from "./Voucher";
import { VoucherFindManyArgs } from "./VoucherFindManyArgs";
import { VoucherWhereUniqueInput } from "./VoucherWhereUniqueInput";
import { VoucherUpdateInput } from "./VoucherUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VoucherControllerBase {
  constructor(
    protected readonly service: VoucherService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Voucher })
  @nestAccessControl.UseRoles({
    resource: "Voucher",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVoucher(
    @common.Body() data: VoucherCreateInput
  ): Promise<Voucher> {
    return await this.service.createVoucher({
      data: {
        ...data,

        tombola: data.tombola
          ? {
              connect: data.tombola,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        code: true,
        createdAt: true,
        id: true,
        isValid: true,

        tombola: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Voucher] })
  @ApiNestedQuery(VoucherFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Voucher",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async vouchers(@common.Req() request: Request): Promise<Voucher[]> {
    const args = plainToClass(VoucherFindManyArgs, request.query);
    return this.service.vouchers({
      ...args,
      select: {
        code: true,
        createdAt: true,
        id: true,
        isValid: true,

        tombola: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Voucher })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Voucher",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async voucher(
    @common.Param() params: VoucherWhereUniqueInput
  ): Promise<Voucher | null> {
    const result = await this.service.voucher({
      where: params,
      select: {
        code: true,
        createdAt: true,
        id: true,
        isValid: true,

        tombola: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Voucher })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Voucher",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVoucher(
    @common.Param() params: VoucherWhereUniqueInput,
    @common.Body() data: VoucherUpdateInput
  ): Promise<Voucher | null> {
    try {
      return await this.service.updateVoucher({
        where: params,
        data: {
          ...data,

          tombola: data.tombola
            ? {
                connect: data.tombola,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          code: true,
          createdAt: true,
          id: true,
          isValid: true,

          tombola: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Voucher })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Voucher",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVoucher(
    @common.Param() params: VoucherWhereUniqueInput
  ): Promise<Voucher | null> {
    try {
      return await this.service.deleteVoucher({
        where: params,
        select: {
          code: true,
          createdAt: true,
          id: true,
          isValid: true,

          tombola: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
